# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8b16edf0e7982e6c76ccda855e95859209bfc526bc4696afa08e19aeab65ec99e6a0a12b12d24ea3e3dd91b27f873cf7d8086193c8bda7dd318bf275680465

test:
  secret_key_base: fea5942840d8463fe663ceb3e9c59a9597f944d84ac047ea3e98574ef637e6c73163bdb89d5fcb9b372e45f25a6b984450ae792d6d45d5a88adc6c294fe1a7a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
